### ISSUE TITLE
Family argument and outputs

### ISSUE THREAD

**Issue by RayCzajaJr** [James-Thorson-NOAA/dsem#26]
When I use a fixed family, all of my outputs make sense (e.g., coefficients and p values seem reasonable). I did some spot checking where I used DSEM for an individual, non lagged relationship and compared output to a simple linear regression of the same two variables, and the outputs are close. However, fixed "assumes that a given variable is measured exactly." This seems like a difficult assumption to satisfy. I see you used fixed though in your vignettes. What was your justification for using fixed?

When I use normal, I get a lot of NaNs (for errors, z values and p values) and ridiculously high coefficients and low p values  (e.g., 2.953052e-29, for non simultaneous effects). Adjusting some dsem_control arguments (e.g., the number of loops and changing gmrf_parameterization to "projection") helps a little, but these issues still persist. 

Any other advice on how to proceed?

**Comment by James-Thorson-NOAA** [comment]
It is often the case that you can't simultaneously estimate process and measurement variance without either (1) having multiple replicated measurements or (2) having some prior on one or the other variance (like assuming a poisson distribution with a known mean-variance relationship).  So family = "fixed" is estimable in a much wider range of cases.  However, I haven't worked out the R2 calcs for a only-process-error model, so that's a drawback.

**Comment by RayCzajaJr** [comment]
Okay, seems like fixed is reasonable. If someone (e.g., a reviewer or co author) were to insist on a measure of variance explained, what about this "band-aid" option... create a multiple regression for each response variable that includes all significant variables (as determined by DSEM). Not ideal, but do you see any MAJOR issue for this (maybe temporary?) solution?

**Comment by James-Thorson-NOAA** [comment]
see response [here](https://github.com/James-Thorson-NOAA/dsem/issues/27)
